### PR TITLE
Step by production metadata

### PR DESCRIPTION
**Pull request by ArtemIsmagilov**
refactoring settings for production by pyproject.toml via declarative

### CODE REVIEW

**Comment by ArtemIsmagilov** [comment]
I want to add a link with a githubaction build attempt so that there are no errors when actually building on PyPi

**Comment by ArtemIsmagilov** [comment]
crush only aarch(

**Comment by ArtemIsmagilov** [comment]
- config based on pyproject.toml
- ready for production
- reday for release
- results https://github.com/ArtemIsmagilov/emcache/actions/runs/9784089846/job/27014219905

**Comment by ArtemIsmagilov** [comment]
Honestly, I just want to be sure when I see the checkboxes for all versions)

**Comment by ArtemIsmagilov** [comment]
I did a little experiment. And the build speed of macos has not changed in any way. It seems to be related to the use of updated download and upload atrifacts to v4

**Comment by pfreixes** [comment]
For now Ill say that Im not interested on moving forward with this one, I would prefer to keep the changes to the minimal and/or just bug fixes.

**Comment by ArtemIsmagilov** [comment]
https://setuptools.pypa.io/en/latest/references/keywords.html

> Users are strongly encouraged to use a declarative config either via [setup.cfg](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html) or [pyproject.toml](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) and only rely on setup.py if they need to tap into special behaviour that requires scripting (such as building C extensions).

**Comment by ArtemIsmagilov** [comment]
How do you feel about us moving the entire configuration from setup.py to setup.cfg? As far as I can tell, pyproject.toml will not be damaged. This may not be your option. I'm ready to provide PR configurations with setup.cfg. This is a non-conflicting and supported setting. What do you think, @pfreixes?

**Pull request closed without merging**
