### PR TITLE
Fix release ci cd

### PR DESCRIPTION
**Pull request by ArtemIsmagilov**
Our pipeline still looks cumbersome. 
I think we need to do separate work on breaking it down into functions, formalizing dependencies so that we can upload by 1 file it to all runners

### CODE REVIEW

**Comment by pfreixes** [comment]
Have you tried the changes that you are proposing in some way?

**Comment by ArtemIsmagilov** [comment]
Yes, there were a lot of attempts, you can look at my Actions. First, try these changes locally and remove the release tokens

**Comment by pfreixes** [comment]
Nice could you please add a link to the CI Action where it shows that the changes proposed are addressing the current issues and all wheels are properly build?

**Comment by ArtemIsmagilov** [comment]
I’ll formalize this with a tag and all the checkboxes and come back with an answer)

**Comment by ArtemIsmagilov** [comment]
For new versions of upload-file astors, I need to update the pipeline a little more; the error only occurs at the version level. I want to try to fix this, otherwise we'll move to version 2
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

**Comment by ArtemIsmagilov** [comment]
we still need to think about how to make wheels for macos for all versions of python

**Comment by ArtemIsmagilov** [comment]
look, this should work https://github.com/ArtemIsmagilov/emcache/actions/runs/9226843980/job/25387743146

**Comment by pfreixes** [comment]
Oks lets give it a try.

**Review by pfreixes — APPROVED** [review]

**Comment by pfreixes** [comment]
It worked, thanks! 🙇

**Pull request merged**
