### PR TITLE
Don't log on connection_lost if conn is closed

### PR DESCRIPTION
**Pull request by chs2**
Ref: https://github.com/emcache/emcache/issues/65

### CODE REVIEW

**Review by pfreixes — APPROVED** [review]

**Comment by chs2** [comment]
@pfreixes, CI fails because of https://github.com/psf/black/issues/2964.

**Comment by pfreixes** [comment]
@chs2 can you update the black version in this PR for addressing the issue?

**Comment by chs2** [comment]
Now it fails (maybe) because of the multi-line regex used by `black`.
https://github.com/emcache/emcache/blob/98219d036ca4984ed714ace5162f2158ad2f6e15/pyproject.toml#L3-L8

But I'm not familiar enough with poetry and/or github CI to find a fix. :(

**Comment by chs2** [comment]
In fact, we're hitting the same as https://github.com/psf/black/issues/2677

In 
https://github.com/emcache/emcache/commit/98219d036ca4984ed714ace5162f2158ad2f6e15#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L6
`\.venv` has been replaced by `\env` which is invalid.

What should it be?

**Comment by pfreixes** [comment]
Thanks!

**Pull request merged**
