### PR TITLE
Unix socket support

### PR DESCRIPTION
**Pull request by jhominal**
I would like to connect to a Unix socket using `emcache`. (Like the person who opened #91) As such, I have begun the work of implementing that feature in the branch above.

I am currently not sure that the changes, as they are proposed in this branch, will work (I will be testing that tomorrow on a memcached instance).

However, I would already be interested in your feedback on at least two points:

 1. How should the public API change in order to support Unix sockets?
   * Should there be an alternate class to `MemcachedHostAddress`, dedicated to Unix sockets (which is the way that the current PR is written), or should the existing `MemcachedHostAddress` class be extended;
   *  What to do with the `Node` class, and its properties `host` and `port`?
   * How should the `cyemcache.RendezvousNode` be changed to support Unix sockets?
   * What to do with the `create_protocol` function in `protocol.py` (that function is a bit annoying because `host`/`port` are the first two arguments... I have decided to make a breaking change in this draft, but it would be possible to avoid breaking changes in this function if you prefer);
 2. What should be the behavior of Unix sockets in Rendezvous hashing?

Thank you.

### CODE REVIEW

**Comment by pfreixes** [comment]
Hey thanks for taking care of this one.

Im wondering if its worth it or even expected that people that uses UnixSockets they would require the following:

- Connect to a set of hosts some of them using TCP addresses and other using Unix addresses
- Connect to multiple Unix addresses

The PR as it is right now provides support for both uses cases, Im wondering if they are expected use cases. On the other hand not limiting the interfaces so still providing support to this "unlikely" - please correct me if Im worng here - use cases, makes the changes easier.

So Im happy to keep the proposal for the contracts using an Union of both type of addresses.

> What to do with the Node class, and its properties host and port?

Im ok with the proposal, maybe if possible I would go for passing to the [create_protocol](https://github.com/emcache/emcache/pull/117/files#diff-07f845da2abf106971aad8cdbb60c413d2cc88fe54d91bb4cebb28b3e4c43de4R313) also one of the other instance instead of using a Tuple.

> How should the cyemcache.RendezvousNode be changed to support Unix sockets?

We could just change the constructor [here](https://github.com/emcache/emcache/blob/master/emcache/_cython/hashing/rendezvous.pyx#L11), and take as a parameter just the `host_and_port_or_unix_socket_path`, behind the scene we can just save the string under a generic field name. The caller, if using TCP addresses will need to provide the concatenation of the host and the port.

With this change everything should work if Im not missing something.

> What to do with the create_protocol function in protocol.py (that function is a bit annoying because host/port are the first two arguments... I have decided to make a breaking change in this draft, but it would be possible to avoid breaking changes in this function if you prefer);

As said before we can try to pass one or the other type, and make the distinction internally checking types. Makes the interfaces more obvious. Since its not a public function we can make breaking changes without any issue.

> What should be the behavior of Unix sockets in Rendezvous hashing?

We will just use the path of the unix socket as an input of the hashing function for calculating the weight of the node, thats all.

**Comment by jhominal** [comment]
Hello,

I have been taken by other tasks so I have not had time to test this PR against an actual service yet.

> I'm wondering if its worth it or even expected that people that uses UnixSockets they would require the following:
>  * Connect to a set of hosts some of them using TCP addresses and other using Unix addresses
>  * Connect to multiple Unix addresses
Just as you surmised, I only expect to connect to a single Unix address. However, I think that a design that treats a Unix socket in the same way as a TCP socket is less intrusive - preventing the hypothetical use cases mentioned requires additional effort, and I do not see why you would want to prevent these use cases (however, I can implement these limitations if you wish).

And from what I gather from your response, you are OK with breaking changes in non-public functions, which makes things easier.

I will amend this PR during this week. As for the testing strategy, I would like to ask:

 * Would you like all tests that are currently done with TCP sockets should also be done with Unix sockets, or would limiting Unix socket tests to a subset of TCP socket tests be acceptable?
 * In the case of a Unix socket test that has the same workflow as an existing TCP socket test, would you prefer for me to duplicate the test main body, or to use `pytest.mark.parametrize`?

**Comment by pfreixes** [comment]
> In the case of a Unix socket test that has the same workflow as an existing TCP socket test, would you prefer for me to duplicate the test main body, or to use pytest.mark.parametrize?

I believe that we can just piggyback on the existing acceptance test for running them all against one Memcached server that is listening to a UNIX socket, we do not need to duplicate all tests and as you suggest we can either use the `pytest.mark.parametrize` for running all of them against a new client that uses a UNIX socket Memcache host, or also we could just extend [this](https://github.com/emcache/emcache/blob/master/tests/acceptance/conftest.py#L22) fixture for adding also a third host that uses UNIX socket.

We will. need to modify also the places where the memcache hosts are instantiated for passing the tests, like this [one](https://github.com/emcache/emcache/blob/master/.github/workflows/ci.yml#L49) or the [docker-compose file](https://github.com/emcache/emcache/blob/master/docker-compose.yml).

**Comment by jhominal** [comment]
Sorry, I had to take a hiatus, I am looking at this again right now.

@pfreixes For this remark, "maybe if possible I would go for passing to the [create_protocol](https://github.com/emcache/emcache/pull/117/files#diff-07f845da2abf106971aad8cdbb60c413d2cc88fe54d91bb4cebb28b3e4c43de4R313) also one of the other instance", I understand that, if possible, you would like the `create_protocol` method to take a `Union[MemcachedHostAddress, MemcachedUnixSocketPath]` as its first argument.

Right now, there is an issue with making that work, which is:

 * `MemcachedHostAddress` and `MemcachedUnixSocketPath` are defined in `node.py`
 * `create_protocol` is defined in `protocol.py`
 * `node.py` depends on `connection_pool.py`, which depends on `protocol.py`
 * naively referencing `MemcachedHostAddress` and `MemcachedUnixSocketPath` would introduce a dependency from `protocol.py` to `node.py`, resulting in a circular dependency;

Now, this circular dependency can be avoided by any of these three solutions:

 1. (As originally proposed by this PR) Avoid using `MemcachedHostAddress` and `MemcachedUnixSocketPath` in either `connection_pool.py` or `protocol.py`, and use a simpler, "raw" type for `address` instead (`Union[Tuple[str, int], str]`);
 2. Put `MemcachedHostAddress` and `MemcachedUnixSocketPath` in a separate file (`address.py`?), which can then be referenced from all of `node.py`, `connection_pool.py`, and `protocol.py`;
 3. Add a dependency from `protocol.py` to `node.py`, but guarded by a `if typing.TYPE_CHECKING` check, and use a forward declaration (either with a `str` annotation, or by using `from __future__ import annotations`)

Which solution would you prefer? If you would like to bikeshed any of the names of files or classes proposed here, feel free to do that.

**Comment by pfreixes** [comment]
Option 2 seems perfect to me!

**Comment by ArtemIsmagilov** [comment]
You've done most of the work to support unix connections in this library. You just have to finish the tests. Let's bring this functionality to the end)

**Comment by jhominal** [comment]
This PR seems ready to me now.

Please feel free to make any feedback that you would like.

**Review by pfreixes — APPROVED** [review]
Thanks for the work! good addition!

**Pull request merged**
