### PR TITLE
Tests wheels python 3.8-3.12 versions on macos

### PR DESCRIPTION
**Pull request by ArtemIsmagilov**
Added wheels 3.8-3.12 versions python for macos in release pipeline

### CODE REVIEW

**Comment by ArtemIsmagilov** [comment]
look, it must working https://github.com/ArtemIsmagilov/emcache/actions/runs/9272873618

**Comment by ArtemIsmagilov** [comment]
Closes #103

**Comment by pfreixes** [comment]
@ArtemIsmagilov aren't they already published https://pypi.org/project/emcache/#files ?

**Comment by ArtemIsmagilov** [comment]
The script is to check that our assembly is downloaded on all versions of python on macos. in master only 3.11 is tested

**Comment by ArtemIsmagilov** [comment]
the test is really useless. it just probably tries to install our wheels depending on the version of python.

**Comment by pfreixes** [comment]
Do you think its worth it this test? technically the CI pipeline should catch up errors with different python versions. The idea of testing it at least once was just for the sake of double check it (for linux we could skip the test for all version but one)

Adding these news explicit steps will make the release slower.

**Comment by ArtemIsmagilov** [comment]
@pfreixes, I agree with you, well, I was clever with the tests. this has already been tested

**Pull request closed without merging**
